### Use DecapBridge auth (required)
##backend:
##  name: git-gateway
##  repo: pmpsites/pmp-hugo
##  branch: main
##  identity_url: https://auth.decapbridge.com/sites/2b00e2a8-e271-4934-9f1d-56ad4cb5ad6c
##  gateway_url: https://gateway.decapbridge.com
##  show_preview_links: true
##
##  # Quickly see who did what (optional)
##  commit_messages:
##    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
##    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
##    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
##    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
##    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
##    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

### Better Decap + Bridge logo (optional)
###logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://pmp-hugo.pages.dev
display_url: https://pmp-hugo.pages.dev
publish_mode: editorial_workflow
show_preview_links: true
backend:
  name: github
  repo: pmpsites/pmp-hugo
  branch: main
  base_url: https://pmp-hugo.pages.dev
  auth_endpoint: /api/auth
  squash_merges: true
  preview_context: 'cloudflare preview deploy'



media_library:
  name: cloudinary
  config:
    cloud_name: pmpartner
    api_key: 168594154229559
    multiple: false
    output_filename_only: false


#publish_mode: editorial_workflow
logo_url: https://pmp-hugo.pages.dev/images/logo-sml.svg


#media_folder: "/img" # Folder where user uploaded files should go
#public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: 'insights' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Insights' # Used in the UI
    label_singular: 'Insight' # Used in the UI, ie: "New Post"
    description: >
      Place Marketing Partners Insights (Blog Posts)
    folder: 'content/insights'
    slug: '{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    editor:
      visualEditing: true
    view_filters:
      - label: Insights
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # all The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: 'hidden', default: 'article', hidden: true }
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Draft', name: 'draft', widget: 'boolean', default: false }      
      - {label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD HH:mm', default: '{{now}}'}
      - {label: "Description(used in Insight cards)", name: "description", widget: "text", required: false}
      - label: "Hero Image"
        name: "image"
        widget: "image"
        required: false
         media_library:
           config:
             default_transformations:
              fetch_format: auto
              width: 700    
              quality: auto
              crop: fill
      - {label: "Social Media Image", name: "socialimage", widget: "image", required: false}         
      - {label: "SEO Description", name: "SEODesc", widget: "text", required: false}
      - {label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      - {label: "Tags", name: "tags", widget: "select", options: ["Strategy","Thinking","News"], multiple: true,required: false}              
      - {label: "Sources/References", name: "sources", widget: "list", fields: [
              {label: "Ref No", name: "refno", widget: "number", required: false},
              {label: "Source", name: "source", widget: "string", required: false},
              {label: "Url", name: "url", widget: "string", required: false },
              {label: "Url Title", name: "urltitle", widget: "string", required: false }],required: false}  
    filter:
          field: "layout"
          value: 'article'               